// -----system global variables-----
String fileName = "max_length";    // current file name generated by the system (don't change)

// -----FreeRTOS objects-----
TaskHandle_t TaskHandle_readData;        // read data task handler
TaskHandle_t TaskHandle_writeData;       // write data task handler
SemaphoreHandle_t mutex_SD;
QueueHandle_t queue_handler;

// -----queue data type definition-----
typedef struct queue_data{
    uint32_t current_time;
    float sensor_example;  // sensor data must be float due to a bug in writing to the sd card
} queue_data;

// -----debug data type definition-----
typedef struct debug_data{
    uint8_t id;
    char msg[ESPNOW_BUFFER_SIZE];
} debug_data;

// -----espnow command data type
typedef struct set_up {
    uint8_t id;
    uint8_t command;
} set_up;